name: Xcode - Build and Analyze

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-15

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Select Xcode 16.4
        run: sudo xcode-select -s /Applications/Xcode_16.4.app
      - name: Set Default Scheme
        id: get-scheme
        run: |
          scheme_list=$(xcodebuild -list -json | tr -d "\n")
          default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['schemes'][0]")
          if [ -z "$default" ]; then
            echo "Error: No valid scheme found!"
            exit 1
          fi
          echo "Using default scheme: $default"
          echo "scheme=$default" >> $GITHUB_OUTPUT
      - name: Build
        run: |
          scheme="${{ steps.get-scheme.outputs.scheme }}"
          if [ "$(ls -A | grep -i \\.xcworkspace\$)" ]; then
            filetype_parameter="workspace"
            file_to_build="$(ls -A | grep -i \\.xcworkspace\$)"
          else
            filetype_parameter="project"
            file_to_build="$(ls -A | grep -i \\.xcodeproj\$)"
          fi

          file_to_build=$(echo $file_to_build | awk '{$1=$1;print}')

          echo "Building with $filetype_parameter: $file_to_build and scheme: $scheme"
          xcodebuild clean build analyze \
            -scheme "$scheme" \
            -"$filetype_parameter" "$file_to_build" \
            -destination 'platform=macOS,arch=arm64,name=My Mac' \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
